---
# tasks file for ansible-redis
## INSTALLATION ##
- include: redis_install.yml
  when:
    ansible_distribution == 'Ubuntu'
    and (ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial')
  tags: [installation]

## ROLLBACK ##
- include: redis_rollback.yml
  when:
    ansible_distribution == 'Ubuntu'
    and (ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial')
  tags: [rollback]

## TESTING ##
- include: redis_testing.yml
  when:
    ansible_distribution == 'Ubuntu'
    and (ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial')
  tags: [testing]
