---
- name: "Optimization - vm.overcommit_memory"
  sysctl:
    name=vm.overcommit_memory
    value=1
    state=present
    reload=yes

- name: "Optimization - net.core.somaxconn"
  sysctl:
    name=net.core.somaxconn
    value=1024
    state=present
    reload=yes

- name: "Enable Transparent Hugepage"
  lineinfile:
    dest="/etc/rc.local"
    line="echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    state=present
  notify: Set Transparent Hugepage
